### PR TITLE
use fix: proper trailing slashes

### LINKED ISSUE #332: URL trailing slashes dev vs production
### Describe the bug
There's difference how develop and production handles trailing slashes, or lack of in the internal links. In production trailing slashes are added to url when page is opened. That's not a case in dev.

### To Reproduce
1. `pnpm run develop`
2. Trailing slashes are not added when opening page, ie. `https://contribute.freecodecamp.org/how-to-translate-files` stays like that.
3. Sidebar highlight and Next/Prev links are working correctly.
vs
1. `pnpm run build && pnpm start` or use production.
2. Trailing slashes are added, ie. `https://contribute.freecodecamp.org/how-to-translate-files` -> `https://contribute.freecodecamp.org/how-to-translate-files/`
3. Sidebar highlight is not working because sidebar links don't use trailing slashes.
4. Similarly Next/Prev links are messed up with actual url containing trailing slashes.

### Expected behavior
Limit the discrepancy between develop and production, to not make it appear working (in dev), when it's actually not working (in production).

### Additional context
- Astro has `trailingSlash` configuration option, which can be used to always use trailing slashes  https://docs.astro.build/en/reference/configuration-reference/#trailingslash. This will however result in develop in `404` error for any link without the trailing slash, so every internal link in sidebar or header would need to have trailing slash added. I had also some troubles with `/FAQ/` it was always redirected to `/faq`.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #332

I wanted to use middleware, but I unfortunately got stumped trying to figure out how to add a backslash to the path. As a result, I manually updated every link I could find.

### CODE REVIEW

File: src/update-pagination.ts [hunk 1]
```diff
@@ -38,77 +41,77 @@ export const content: Section[] = [
     title: 'sidebar.code_contribution',
     contents: [
       {
-        href: '/how-to-setup-freecodecamp-locally',
+        href: 'how-to-setup-freecodecamp-locally/',
```
Comment (gikf) [inline src/update-pagination.ts]:
```suggestion
        href: '/how-to-setup-freecodecamp-locally/',
```
Otherwise the link will be messed up - `/{current page}/how-to-setup-freecodecamp-locally/`.

Ie. on `/how-to-proofread-files/` link will be `/how-to-proofread-files/how-to-setup-freecodecamp-locally/`

Comment (a2937) [reply src/update-pagination.ts]: Okay it should be fixed now.

**Review by raisedadead — APPROVED** [review]
